import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';

import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Navbar from '../../components/Navbar'

// export function generateStaticParams() {

//   return routing.locales.map((locale) => ({locale}));
// }

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
        <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
